-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.autocmds")
require("config.gruvbox")
require("config.keymaps")
require("config.terminal")
require("config.remove_powershell")
require("config.python_env")
require("config.powershell")
require("config.jdtls")
